### PR TITLE
Fix exception on 1.19.4 servers

### PR DESCRIPTION
**Pull request by BlockyTheDev**

### CODE REVIEW

**Comment by BlockyTheDev** [comment]
Report: https://discord.com/channels/522474178746646558/522501516624396288/1096296777088499812

**Comment by BlockyTheDev** [comment]
Now it is the correct NMS version `v1_19_R3`

**Comment by BlockyTheDev** [comment]
@RodneyMKay Ready for review & merge

**Comment by RodneyMKay** [comment]
I found another mapping change during testing. I just fixed it (I hope you don't mind). I haven't really been on this side of code reviews yet, so I wasn't sure whether to comment and ask you to fix it. It felt rude to do that though, since I had the fix written already.

**Comment by BlockyTheDev** [comment]
> I found another mapping change during testing. I just fixed it (I hope you don't mind). I haven't really been on this side of code reviews yet, so I wasn't sure whether to comment and ask you to fix it. It felt rude to do that though, since I had the fix written already.

No problem. I couldn't test it because I wasn't at my main device. For such reasons I am setting the check mark for editing by maintainers.

**Pull request merged**
